version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5433:5432" 
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@db:5432/testdb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test_network

networks:
  test_network:

volumes:
  pgdata_test: