version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb?sslmode=disable
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - db

volumes:
  pgdata:
  