CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    firstname VARCHAR(100),
    lastname VARCHAR(100),
    email VARCHAR(100),
    age INT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);